const Menu = [
    {
        id: 1,
        locatin: '8554 London',
        descption: 'Westminster is the political and cultural heart of London.It home to iconic land',
        city: 'London',
        room: ' 3Room',
        bed: ' 4Bed',
        bath: ' 1Bath',
        price:'$7,255/month',
        squrefit: ' 732sft',
       image: "./image/tede.jpg"
    },
    {
        id: 2,
        locatin: '6645 Chelsea',
        descption: ' Known for its affluent and artistic community, Chelsea features trendy boutiques',
        city: 'London',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        price:'$7,255/month',
        squrefit: '732sft',
        image: "./image/imag.jpeg"
    },
    {
        id: 3,
        locatin: '66485 Camden',
        descption: ' Camden is famous for its vibrant markets, live music venues, and alternative culture. ',
        city: 'London',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        price:'$7,255/month',
        squrefit: '732sft',
       image: "./image/tede.jpg"
    },
    {
        id: 4,
        locatin: '1554 Greenwich',
        descption: 'Greenwich is known for the Royal Observatory and the Prime Meridian, marking the start',
        city: 'London',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        price:'$7,255/month',
        squrefit: '732sft',
       image: "./image/ii.jpeg"
    },
    {
        id: 5,
        locatin: '8637 Islington',
        descption: 'Islington is a trendy district filled with fashionable shops, restaurants, and a lively',
        city: 'London',
        room: '3Room',
        bed: '4Bed',
        price:'$7,255/month',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/imag.jpeg"
    },
    {
        id: 6,
        locatin: '7683 ',
        descption: 'Kensington is an elegant district with some of Londons most prestigious museums',
        city: 'London',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        price:'$7,255/month',
        squrefit: '732sft',
       image: "./image/imag.jpeg"
    },
    
    {
        id: 7,
        locatin: '5343 Paris',
        descption: 'The capital city of France and a global center for art, fashion, culture, and history.',
        city: 'Paris',
        price:'$7,255/month',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/ii.jpeg"
    },
    {
        id: 8,
        locatin: '753 Versailles',
        descption: 'Famous for the opulent Palace of Versailles, a symbol of absolute monarchy in France',
        city: 'Paris',
        room: '3Room',
        price:'$7,255/month',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/tede.jpg"
    },
    {
        id: 9,
        locatin: '3387 Saint-Denis',
        descption: 'Known for the stunning Basilica of Saint-Denis, the burial place of French monarchs',
        city: 'Paris',
        price:'$7,255/month',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/imag.jpeg"
    },
    {
        id: 10,
        locatin: '786 Boulogne-Billancourt',
        descption: 'A suburb of Paris known for its picturesque park, Parc des Princes stadium',
        city: 'Paris',
        room: '3Room',
        price:'$7,255/month',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/ii.jpeg"
    },
    {
        id: 11,
        locatin: '7678 Nanterre',
        descption: 'Home to the modern La Défense business district, Nanterre also has a rich historical ',
        city: 'Paris',
        price:'$7,255/month',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/imag.jpeg"
    },
    {
        id: 12,
        locatin: '7366 Montreuil',
        descption: 'A multicultural suburb known for its artistic community, parks, and vibrant street art scene',
        city: 'Paris',
        room: '3Room',
        price:'$7,255/month',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/tede.jpg"
    },
   
    {
        id: 13,
        locatin: '6378 Mumbai',
        descption: 'The capital city of the Indian state of Maharashtra and the most populous city in India',
        city: 'Mumbai',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        price:'$7,255/month',
        squrefit: '732sft',
       image: "./image/ii.jpeg"
    },
    {
        id: 14,
        locatin: '5378 Navi Mumbai',
        descption: 'A planned township located across the harbor from Mumbai',
        city: 'Mumbai',
        price:'$7,255/month',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/imag.jpeg"
    },
    {
        id: 15,
        locatin: '5376 Thane',
        descption: 'A city to the northeast of Mumbai, Thane is known for its historical sites',
        city: 'Mumbai',
        price:'$7,255/month',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/imag.jpeg"
    },
    {
        id: 16,
        locatin: '3765 Kalyan-Dombivli',
        descption: 'Twin cities located in the Thane district, known for their residential areas',
        city: 'Mumbai',
        price:'$7,255/month',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/tede.jpg"
    },
    {
        id: 17,
        locatin: '7867 Vasai-Virar',
        descption: 'A city located to the northwest of Mumbai, known for its beautiful beaches and historical forts.',
        city: 'Mumbai',
        room: '3Room',
        price:'$7,255/month',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/ii.jpeg"
    },
    {
        id: 18,
        locatin: '5367 PuneWhile not part of Mumbai, Pune is a major city in Maharashtra, known for its educational',
        descption: '',
        city: 'Mumbai',
        price:'$7,255/month',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/imag.jpeg"
    },
   
    {
        id: 19,
        locatin: '6786 NewYorkCity',
        descption: 'he largest city in the state and one of the most populous cities city in the state ',
        city: 'NewYork',
        price:'$7,255/month',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/tede.jpg"
    },
    {
        id: 20,
        locatin: '67856 Buffalo',
        descption: 'Located in western New York, Buffalo is known for its historical architecture',
        city: 'NewYork',
        price:'$7,255/month',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/imag.jpeg"
    },
    {
        id: 21,
        locatin: '5865 Rochester',
        descption: 'Known as the "Flower City," Rochester is famous for its contributions to photography',
        city: 'NewYork',
        room: '3Room',
        price:'$7,255/month',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/ii.jpeg"
    },
    {
        id: 22,
        locatin: '573Syracuse',
        descption: 'Home to Syracuse University and a hub for education, healthcare',
        city: 'NewYork',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        price:'$7,255/month',
        squrefit: '732sft',
       image: "./image/imag.jpeg"
    },
    {
        id: 23,
        locatin: '37863 Albany',
        descption: 'he state capital of New York, Albany is located in the eastern part ',
        city: 'NewYork',
        room: '3Room',
        price:'$7,255/month',
        bed: '4Bed',
        bath: '1Bath',
        squrefit: '732sft',
       image: "./image/tede.jpg"
    },
    {
        id:24,
        locatin: '7637 Yonkers',
        descption: 'A city in Westchester County, Yonkers is known for its suburban',
        city: 'NewYork',
        room: '3Room',
        bed: '4Bed',
        bath: '1Bath',
        price:'$7,255/month',
        squrefit: '732sft',
       image: "./image/ii.jpeg"
    },
   



];
export default Menu;